In [ ]:
"""  
- Pandas is an open source Python package that is most widely used for data science/data analysis

- It works with large data sets

"""

In [ ]:
"""  
It uses 3 Datastructures
    - Series
    - Data frames
    - Panel


Series deals with 1D array

Data frames deals with 2D array

Panel deals with multi dimension array

"""

In [ ]:
"""
import pandas as pd 

pd.Series(data,index) 

pd.DataFrame(data) 

pd.Panel(data,major axis,minor axis,dtype)

"""

In [12]:
# Creating empty series
import pandas as pd

S=pd.Series()

print(S)

Series([], dtype: float64)

C:\Users\SAGAR\AppData\Local\Temp\ipykernel_10756\1792576823.py:4: DeprecationWarning: The default dtype for empty Series will be 'object' instead of 'float64' in a future version. Specify a dtype explicitly to silence this warning.
  S=pd.Series()

In [23]:
import pandas as pd
import numpy as np

a= np.array([10,20,30,40])
S=pd.Series(a, dtype='float16')
print(S)

0    10.0
1    20.0
2    30.0
3    40.0
dtype: float16

In [24]:
import pandas as pd

a = [10,70,20]

myvar = pd.Series(a, index=['x','y','z'])

print(myvar)

x    10
y    70
z    20
dtype: int64

In [25]:
import pandas as pd

a = [10,70,20]

myvar = pd.Series(a, index=['x','y','z'])

print(myvar['y'])

70

In [26]:
L=[10,20,30,40]

pd.Series(L)

0    10
1    20
2    30
3    40
dtype: int64

In [27]:
import pandas as pd

sales = {"day1":42, "day2":38, "day3":39}

myvar = pd.Series(sales)

print(myvar)

day1    42
day2    38
day3    39
dtype: int64

In [41]:
import pandas as pd

data = {
    "calories" : [420,380,390],
    "duration" : [50,40,45]
}


myvar = pd.DataFrame(data,index=['calories','duration','Other'])

print(myvar)

          calories  duration
calories       420        50
duration       380        40
Other          390        45

In [42]:
print(myvar.loc['calories'])

calories    420
duration     50
Name: calories, dtype: int64

In [43]:
#print(myvar.loc[[0]])

In [44]:
#print(myvar.loc[[0,1]])

In [45]:
import pandas as pd

sales = {
    "price": [120,280,390],
    "pieces":[50,40,45]
    }

myvar = pd.DataFrame(sales,index=['day1','day2','day3'])

print(myvar)

      price  pieces
day1    120      50
day2    280      40
day3    390      45

In [46]:
print(myvar.loc['day2'])

price     280
pieces     40
Name: day2, dtype: int64

In [ ]:
"""  
Loading data from excel file: read_excel
Loading data from CSV file: read_csv


Loading excel file
import pandas as pd
Df=pd.read_excel(“path”)

Loading csv file
import pandas as pd
Df=pd.read_csv(“path”) 



Big data sets are often stored, or extracted as JSON.

import pandas as pd
df = pd.read_json('data.json')
print(df.to_string()) 

"""

Reading CSV using Pandas

In [51]:
import pandas as pd

df = pd.read_csv('student_data.csv')

print(df.to_string())

    school sex  age address famsize Pstatus  Medu  Fedu      Mjob      Fjob      reason guardian  traveltime  studytime  failures schoolsup famsup paid activities nursery higher internet romantic  famrel  freetime  goout  Dalc  Walc  health  absences  G1  G2  G3
0       GP   F   18       U     GT3       A     4     4   at_home   teacher      course   mother           2          2         0       yes     no   no         no     yes    yes       no       no       4         3      4     1     1       3         6   5   6   6
1       GP   F   17       U     GT3       T     1     1   at_home     other      course   father           1          2         0        no    yes   no         no      no    yes      yes       no       5         3      3     1     1       3         4   5   5   6
2       GP   F   15       U     LE3       T     1     1   at_home     other       other   mother           1          2         3       yes     no  yes         no     yes    yes      yes       no       4         3      2     2     3       3        10   7   8  10
3       GP   F   15       U     GT3       T     4     2    health  services        home   mother           1          3         0        no    yes  yes        yes     yes    yes      yes      yes       3         2      2     1     1       5         2  15  14  15
4       GP   F   16       U     GT3       T     3     3     other     other        home   father           1          2         0        no    yes  yes         no     yes    yes       no       no       4         3      2     1     2       5         4   6  10  10
5       GP   M   16       U     LE3       T     4     3  services     other  reputation   mother           1          2         0        no    yes  yes        yes     yes    yes      yes       no       5         4      2     1     2       5        10  15  15  15
6       GP   M   16       U     LE3       T     2     2     other     other        home   mother           1          2         0        no     no   no         no     yes    yes      yes       no       4         4      4     1     1       3         0  12  12  11
7       GP   F   17       U     GT3       A     4     4     other   teacher        home   mother           2          2         0       yes    yes   no         no     yes    yes       no       no       4         1      4     1     1       1         6   6   5   6
8       GP   M   15       U     LE3       A     3     2  services     other        home   mother           1          2         0        no    yes  yes         no     yes    yes      yes       no       4         2      2     1     1       1         0  16  18  19
9       GP   M   15       U     GT3       T     3     4     other     other        home   mother           1          2         0        no    yes  yes        yes     yes    yes      yes       no       5         5      1     1     1       5         0  14  15  15
10      GP   F   15       U     GT3       T     4     4   teacher    health  reputation   mother           1          2         0        no    yes  yes         no     yes    yes      yes       no       3         3      3     1     2       2         0  10   8   9
11      GP   F   15       U     GT3       T     2     1  services     other  reputation   father           3          3         0        no    yes   no        yes     yes    yes      yes       no       5         2      2     1     1       4         4  10  12  12
12      GP   M   15       U     LE3       T     4     4    health  services      course   father           1          1         0        no    yes  yes        yes     yes    yes      yes       no       4         3      3     1     3       5         2  14  14  14
13      GP   M   15       U     GT3       T     4     3   teacher     other      course   mother           2          2         0        no    yes  yes         no     yes    yes      yes       no       5         4      3     1     2       3         2  10  10  11
14      GP   M   15       U     GT3       A     2     2     other     other        home    other           1          3         0        no    yes   no         no     yes    yes      yes      yes       4         5      2     1     1       3         0  14  16  16
15      GP   F   16       U     GT3       T     4     4    health     other        home   mother           1          1         0        no    yes   no         no     yes    yes      yes       no       4         4      4     1     2       2         4  14  14  14
16      GP   F   16       U     GT3       T     4     4  services  services  reputation   mother           1          3         0        no    yes  yes        yes     yes    yes      yes       no       3         2      3     1     2       2         6  13  14  14
17      GP   F   16       U     GT3       T     3     3     other     other  reputation   mother           3          2         0       yes    yes   no        yes     yes    yes       no       no       5         3      2     1     1       4         4   8  10  10
18      GP   M   17       U     GT3       T     3     2  services  services      course   mother           1          1         3        no    yes   no        yes     yes    yes      yes       no       5         5      5     2     4       5        16   6   5   5
19      GP   M   16       U     LE3       T     4     3    health     other        home   father           1          1         0        no     no  yes        yes     yes    yes      yes       no       3         1      3     1     3       5         4   8  10  10
20      GP   M   15       U     GT3       T     4     3   teacher     other  reputation   mother           1          2         0        no     no   no         no     yes    yes      yes       no       4         4      1     1     1       1         0  13  14  15
21      GP   M   15       U     GT3       T     4     4    health    health       other   father           1          1         0        no    yes  yes         no     yes    yes      yes       no       5         4      2     1     1       5         0  12  15  15
22      GP   M   16       U     LE3       T     4     2   teacher     other      course   mother           1          2         0        no     no   no        yes     yes    yes      yes       no       4         5      1     1     3       5         2  15  15  16
23      GP   M   16       U     LE3       T     2     2     other     other  reputation   mother           2          2         0        no    yes   no        yes     yes    yes      yes       no       5         4      4     2     4       5         0  13  13  12
24      GP   F   15       R     GT3       T     2     4  services    health      course   mother           1          3         0       yes    yes  yes        yes     yes    yes      yes       no       4         3      2     1     1       5         2  10   9   8
25      GP   F   16       U     GT3       T     2     2  services  services        home   mother           1          1         2        no    yes  yes         no      no    yes      yes       no       1         2      2     1     3       5        14   6   9   8
26      GP   M   15       U     GT3       T     2     2     other     other        home   mother           1          1         0        no    yes  yes         no     yes    yes      yes       no       4         2      2     1     2       5         2  12  12  11
27      GP   M   15       U     GT3       T     4     2    health  services       other   mother           1          1         0        no     no  yes         no     yes    yes      yes       no       2         2      4     2     4       1         4  15  16  15
28      GP   M   16       U     LE3       A     3     4  services     other        home   mother           1          2         0       yes    yes   no        yes     yes    yes      yes       no       5         3      3     1     1       5         4  11  11  11
29      GP   M   16       U     GT3       T     4     4   teacher   teacher        home   mother           1          2         0        no    yes  yes        yes     yes    yes      yes      yes       4         4      5     5     5       5        16  10  12  11
30      GP   M   15       U     GT3       T     4     4    health  services        home   mother           1          2         0        no    yes  yes         no      no    yes      yes       no       5         4      2     3     4       5         0   9  11  12
31      GP   M   15       U     GT3       T     4     4  services  services  reputation   mother           2          2         0        no    yes   no        yes     yes    yes      yes       no       4         3      1     1     1       5         0  17  16  17
32      GP   M   15       R     GT3       T     4     3   teacher   at_home      course   mother           1          2         0        no    yes   no        yes     yes    yes      yes      yes       4         5      2     1     1       5         0  17  16  16
33      GP   M   15       U     LE3       T     3     3     other     other      course   mother           1          2         0        no     no   no        yes      no    yes      yes       no       5         3      2     1     1       2         0   8  10  12
34      GP   M   16       U     GT3       T     3     2     other     other        home   mother           1          1         0        no    yes  yes         no      no    yes      yes       no       5         4      3     1     1       5         0  12  14  15
35      GP   F   15       U     GT3       T     2     3     other     other       other   father           2          1         0        no    yes   no        yes     yes    yes       no       no       3         5      1     1     1       5         0   8   7   6
36      GP   M   15       U     LE3       T     4     3   teacher  services        home   mother           1          3         0        no    yes   no        yes     yes    yes      yes       no       5         4      3     1     1       4         2  15  16  18
37      GP   M   16       R     GT3       A     4     4     other   teacher  reputation   mother           2          3         0        no    yes   no        yes     yes    yes      yes      yes       2         4      3     1     1       5         7  15  16  15
38      GP   F   15       R     GT3       T     3     4  services    health      course   mother           1          3         0       yes    yes  yes        yes     yes    yes      yes       no       4         3      2     1     1       5         2  12  12  11
39      GP   F   15       R     GT3       T     2     2   at_home     other  reputation   mother           1          1         0       yes    yes  yes        yes     yes    yes       no       no       4         3      1     1     1       2         8  14  13  13
40      GP   F   16       U     LE3       T     2     2     other     other        home   mother           2          2         1        no    yes   no        yes      no    yes      yes      yes       3         3      3     1     2       3        25   7  10  11
41      GP   M   15       U     LE3       T     4     4   teacher     other        home    other           1          1         0        no    yes   no         no      no    yes      yes      yes       5         4      3     2     4       5         8  12  12  12
42      GP   M   15       U     GT3       T     4     4  services   teacher      course   father           1          2         0        no    yes   no        yes     yes    yes      yes       no       4         3      3     1     1       5         2  19  18  18
43      GP   M   15       U     GT3       T     2     2  services  services      course   father           1          1         0       yes    yes   no         no     yes    yes      yes       no       5         4      1     1     1       1         0   8   8  11
44      GP   F   16       U     LE3       T     2     2     other   at_home      course   father           2          2         1       yes     no   no        yes     yes    yes      yes       no       4         3      3     2     2       5        14  10  10   9
45      GP   F   15       U     LE3       A     4     3     other     other      course   mother           1          2         0       yes    yes  yes        yes     yes    yes      yes      yes       5         2      2     1     1       5         8   8   8   6
46      GP   F   16       U     LE3       A     3     3     other  services        home   mother           1          2         0        no    yes   no         no     yes    yes      yes       no       2         3      5     1     4       3        12  11  12  11
47      GP   M   16       U     GT3       T     4     3    health  services  reputation   mother           1          4         0        no     no   no        yes     yes    yes      yes       no       4         2      2     1     1       2         4  19  19  20
48      GP   M   15       U     GT3       T     4     2   teacher     other        home   mother           1          2         0        no    yes  yes         no     yes    yes       no       no       4         3      3     2     2       5         2  15  15  14
49      GP   F   15       U     GT3       T     4     4  services   teacher       other   father           1          2         1       yes    yes   no        yes      no    yes      yes       no       4         4      4     1     1       3         2   7   7   7
50      GP   F   16       U     LE3       T     2     2  services  services      course   mother           3          2         0        no    yes  yes         no     yes    yes      yes       no       4         3      3     2     3       4         2  12  13  13
51      GP   F   15       U     LE3       T     4     2    health     other       other   mother           1          2         0        no    yes  yes         no     yes    yes      yes       no       4         3      3     1     1       5         2  11  13  13
52      GP   M   15       U     LE3       A     4     2    health    health       other   father           2          1         1        no     no   no         no     yes    yes       no       no       5         5      5     3     4       5         6  11  11  10
53      GP   F   15       U     GT3       T     4     4  services  services      course   mother           1          1         0       yes    yes  yes         no     yes    yes      yes       no       3         3      4     2     3       5         0   8  10  11
54      GP   F   15       U     LE3       A     3     3     other     other       other   mother           1          1         0        no     no  yes         no     yes    yes      yes       no       5         3      4     4     4       1         6  10  13  13
55      GP   F   16       U     GT3       A     2     1     other     other       other   mother           1          2         0        no     no  yes        yes     yes    yes      yes      yes       5         3      4     1     1       2         8   8   9  10
56      GP   F   15       U     GT3       A     4     3  services  services  reputation   mother           1          2         0        no    yes  yes        yes     yes    yes      yes       no       4         3      2     1     1       1         0  14  15  15
57      GP   M   15       U     GT3       T     4     4   teacher    health  reputation   mother           1          2         0        no    yes   no        yes     yes    yes       no       no       3         2      2     1     1       5         4  14  15  15
58      GP   M   15       U     LE3       T     1     2     other   at_home        home   father           1          2         0       yes    yes   no        yes     yes    yes      yes       no       4         3      2     1     1       5         2   9  10   9
59      GP   F   16       U     GT3       T     4     2  services     other      course   mother           1          2         0        no    yes   no         no     yes    yes      yes       no       4         2      3     1     1       5         2  15  16  16
60      GP   F   16       R     GT3       T     4     4    health   teacher       other   mother           1          2         0        no    yes   no        yes     yes    yes       no       no       2         4      4     2     3       4         6  10  11  11
61      GP   F   16       U     GT3       T     1     1  services  services      course   father           4          1         0       yes    yes   no        yes      no    yes      yes      yes       5         5      5     5     5       5         6  10   8  11
62      GP   F   16       U     LE3       T     1     2     other  services  reputation   father           1          2         0       yes     no   no        yes     yes    yes      yes       no       4         4      3     1     1       1         4   8  10   9
63      GP   F   16       U     GT3       T     4     3   teacher    health        home   mother           1          3         0       yes    yes  yes        yes     yes    yes      yes       no       3         4      4     2     4       4         2  10   9   9
64      GP   F   15       U     LE3       T     4     3  services  services  reputation   father           1          2         0       yes     no   no        yes     yes    yes      yes      yes       4         4      4     2     4       2         0  10  10  10
65      GP   F   16       U     LE3       T     4     3   teacher  services      course   mother           3          2         0        no    yes   no        yes     yes    yes      yes       no       5         4      3     1     2       1         2  16  15  15
66      GP   M   15       U     GT3       A     4     4     other  services  reputation   mother           1          4         0        no    yes   no        yes      no    yes      yes      yes       1         3      3     5     5       3         4  13  13  12
67      GP   F   16       U     GT3       T     3     1  services     other      course   mother           1          4         0       yes    yes  yes         no     yes    yes      yes       no       4         3      3     1     2       5         4   7   7   6
68      GP   F   15       R     LE3       T     2     2    health  services  reputation   mother           2          2         0       yes    yes  yes         no     yes    yes      yes       no       4         1      3     1     3       4         2   8   9   8
69      GP   F   15       R     LE3       T     3     1     other     other  reputation   father           2          4         0        no    yes   no         no      no    yes      yes       no       4         4      2     2     3       3        12  16  16  16
70      GP   M   16       U     GT3       T     3     1     other     other  reputation   father           2          4         0        no    yes  yes         no     yes    yes      yes       no       4         3      2     1     1       5         0  13  15  15
71      GP   M   15       U     GT3       T     4     2     other     other      course   mother           1          4         0        no     no   no         no     yes    yes      yes       no       3         3      3     1     1       3         0  10  10  10
72      GP   F   15       R     GT3       T     1     1     other     other  reputation   mother           1          2         2       yes    yes   no         no      no    yes      yes      yes       3         3      4     2     4       5         2   8   6   5
73      GP   M   16       U     GT3       T     3     1     other     other  reputation   mother           1          1         0        no     no   no        yes     yes    yes       no       no       5         3      2     2     2       5         2  12  12  14
74      GP   F   16       U     GT3       T     3     3     other  services        home   mother           1          2         0       yes    yes  yes        yes     yes    yes      yes       no       4         3      3     2     4       5        54  11  12  11

Reading Excel file in Pandas

In [54]:
import pandas as pd

df = pd.read_excel('student_data.xlsx')

print(df.to_string())

    school sex  age address famsize Pstatus  Medu  Fedu      Mjob      Fjob      reason guardian  traveltime  studytime  failures schoolsup famsup paid activities nursery higher internet romantic  famrel  freetime  goout  Dalc  Walc  health  absences  G1  G2  G3
0       GP   F   18       U     GT3       A     4     4   at_home   teacher      course   mother           2          2         0       yes     no   no         no     yes    yes       no       no       4         3      4     1     1       3         6   5   6   6
1       GP   F   17       U     GT3       T     1     1   at_home     other      course   father           1          2         0        no    yes   no         no      no    yes      yes       no       5         3      3     1     1       3         4   5   5   6
2       GP   F   15       U     LE3       T     1     1   at_home     other       other   mother           1          2         3       yes     no  yes         no     yes    yes      yes       no       4         3      2     2     3       3        10   7   8  10
3       GP   F   15       U     GT3       T     4     2    health  services        home   mother           1          3         0        no    yes  yes        yes     yes    yes      yes      yes       3         2      2     1     1       5         2  15  14  15
4       GP   F   16       U     GT3       T     3     3     other     other        home   father           1          2         0        no    yes  yes         no     yes    yes       no       no       4         3      2     1     2       5         4   6  10  10
5       GP   M   16       U     LE3       T     4     3  services     other  reputation   mother           1          2         0        no    yes  yes        yes     yes    yes      yes       no       5         4      2     1     2       5        10  15  15  15
6       GP   M   16       U     LE3       T     2     2     other     other        home   mother           1          2         0        no     no   no         no     yes    yes      yes       no       4         4      4     1     1       3         0  12  12  11
7       GP   F   17       U     GT3       A     4     4     other   teacher        home   mother           2          2         0       yes    yes   no         no     yes    yes       no       no       4         1      4     1     1       1         6   6   5   6
8       GP   M   15       U     LE3       A     3     2  services     other        home   mother           1          2         0        no    yes  yes         no     yes    yes      yes       no       4         2      2     1     1       1         0  16  18  19
9       GP   M   15       U     GT3       T     3     4     other     other        home   mother           1          2         0        no    yes  yes        yes     yes    yes      yes       no       5         5      1     1     1       5         0  14  15  15
10      GP   F   15       U     GT3       T     4     4   teacher    health  reputation   mother           1          2         0        no    yes  yes         no     yes    yes      yes       no       3         3      3     1     2       2         0  10   8   9
11      GP   F   15       U     GT3       T     2     1  services     other  reputation   father           3          3         0        no    yes   no        yes     yes    yes      yes       no       5         2      2     1     1       4         4  10  12  12
12      GP   M   15       U     LE3       T     4     4    health  services      course   father           1          1         0        no    yes  yes        yes     yes    yes      yes       no       4         3      3     1     3       5         2  14  14  14
13      GP   M   15       U     GT3       T     4     3   teacher     other      course   mother           2          2         0        no    yes  yes         no     yes    yes      yes       no       5         4      3     1     2       3         2  10  10  11
14      GP   M   15       U     GT3       A     2     2     other     other        home    other           1          3         0        no    yes   no         no     yes    yes      yes      yes       4         5      2     1     1       3         0  14  16  16
15      GP   F   16       U     GT3       T     4     4    health     other        home   mother           1          1         0        no    yes   no         no     yes    yes      yes       no       4         4      4     1     2       2         4  14  14  14
16      GP   F   16       U     GT3       T     4     4  services  services  reputation   mother           1          3         0        no    yes  yes        yes     yes    yes      yes       no       3         2      3     1     2       2         6  13  14  14
17      GP   F   16       U     GT3       T     3     3     other     other  reputation   mother           3          2         0       yes    yes   no        yes     yes    yes       no       no       5         3      2     1     1       4         4   8  10  10
18      GP   M   17       U     GT3       T     3     2  services  services      course   mother           1          1         3        no    yes   no        yes     yes    yes      yes       no       5         5      5     2     4       5        16   6   5   5
19      GP   M   16       U     LE3       T     4     3    health     other        home   father           1          1         0        no     no  yes        yes     yes    yes      yes       no       3         1      3     1     3       5         4   8  10  10
20      GP   M   15       U     GT3       T     4     3   teacher     other  reputation   mother           1          2         0        no     no   no         no     yes    yes      yes       no       4         4      1     1     1       1         0  13  14  15
21      GP   M   15       U     GT3       T     4     4    health    health       other   father           1          1         0        no    yes  yes         no     yes    yes      yes       no       5         4      2     1     1       5         0  12  15  15
22      GP   M   16       U     LE3       T     4     2   teacher     other      course   mother           1          2         0        no     no   no        yes     yes    yes      yes       no       4         5      1     1     3       5         2  15  15  16
23      GP   M   16       U     LE3       T     2     2     other     other  reputation   mother           2          2         0        no    yes   no        yes     yes    yes      yes       no       5         4      4     2     4       5         0  13  13  12
24      GP   F   15       R     GT3       T     2     4  services    health      course   mother           1          3         0       yes    yes  yes        yes     yes    yes      yes       no       4         3      2     1     1       5         2  10   9   8
25      GP   F   16       U     GT3       T     2     2  services  services        home   mother           1          1         2        no    yes  yes         no      no    yes      yes       no       1         2      2     1     3       5        14   6   9   8
26      GP   M   15       U     GT3       T     2     2     other     other        home   mother           1          1         0        no    yes  yes         no     yes    yes      yes       no       4         2      2     1     2       5         2  12  12  11
27      GP   M   15       U     GT3       T     4     2    health  services       other   mother           1          1         0        no     no  yes         no     yes    yes      yes       no       2         2      4     2     4       1         4  15  16  15
28      GP   M   16       U     LE3       A     3     4  services     other        home   mother           1          2         0       yes    yes   no        yes     yes    yes      yes       no       5         3      3     1     1       5         4  11  11  11
29      GP   M   16       U     GT3       T     4     4   teacher   teacher        home   mother           1          2         0        no    yes  yes        yes     yes    yes      yes      yes       4         4      5     5     5       5        16  10  12  11
30      GP   M   15       U     GT3       T     4     4    health  services        home   mother           1          2         0        no    yes  yes         no      no    yes      yes       no       5         4      2     3     4       5         0   9  11  12
31      GP   M   15       U     GT3       T     4     4  services  services  reputation   mother           2          2         0        no    yes   no        yes     yes    yes      yes       no       4         3      1     1     1       5         0  17  16  17
32      GP   M   15       R     GT3       T     4     3   teacher   at_home      course   mother           1          2         0        no    yes   no        yes     yes    yes      yes      yes       4         5      2     1     1       5         0  17  16  16
33      GP   M   15       U     LE3       T     3     3     other     other      course   mother           1          2         0        no     no   no        yes      no    yes      yes       no       5         3      2     1     1       2         0   8  10  12
34      GP   M   16       U     GT3       T     3     2     other     other        home   mother           1          1         0        no    yes  yes         no      no    yes      yes       no       5         4      3     1     1       5         0  12  14  15
35      GP   F   15       U     GT3       T     2     3     other     other       other   father           2          1         0        no    yes   no        yes     yes    yes       no       no       3         5      1     1     1       5         0   8   7   6
36      GP   M   15       U     LE3       T     4     3   teacher  services        home   mother           1          3         0        no    yes   no        yes     yes    yes      yes       no       5         4      3     1     1       4         2  15  16  18
37      GP   M   16       R     GT3       A     4     4     other   teacher  reputation   mother           2          3         0        no    yes   no        yes     yes    yes      yes      yes       2         4      3     1     1       5         7  15  16  15
38      GP   F   15       R     GT3       T     3     4  services    health      course   mother           1          3         0       yes    yes  yes        yes     yes    yes      yes       no       4         3      2     1     1       5         2  12  12  11
39      GP   F   15       R     GT3       T     2     2   at_home     other  reputation   mother           1          1         0       yes    yes  yes        yes     yes    yes       no       no       4         3      1     1     1       2         8  14  13  13
40      GP   F   16       U     LE3       T     2     2     other     other        home   mother           2          2         1        no    yes   no        yes      no    yes      yes      yes       3         3      3     1     2       3        25   7  10  11
41      GP   M   15       U     LE3       T     4     4   teacher     other        home    other           1          1         0        no    yes   no         no      no    yes      yes      yes       5         4      3     2     4       5         8  12  12  12
42      GP   M   15       U     GT3       T     4     4  services   teacher      course   father           1          2         0        no    yes   no        yes     yes    yes      yes       no       4         3      3     1     1       5         2  19  18  18
43      GP   M   15       U     GT3       T     2     2  services  services      course   father           1          1         0       yes    yes   no         no     yes    yes      yes       no       5         4      1     1     1       1         0   8   8  11
44      GP   F   16       U     LE3       T     2     2     other   at_home      course   father           2          2         1       yes     no   no        yes     yes    yes      yes       no       4         3      3     2     2       5        14  10  10   9
45      GP   F   15       U     LE3       A     4     3     other     other      course   mother           1          2         0       yes    yes  yes        yes     yes    yes      yes      yes       5         2      2     1     1       5         8   8   8   6
46      GP   F   16       U     LE3       A     3     3     other  services        home   mother           1          2         0        no    yes   no         no     yes    yes      yes       no       2         3      5     1     4       3        12  11  12  11
47      GP   M   16       U     GT3       T     4     3    health  services  reputation   mother           1          4         0        no     no   no        yes     yes    yes      yes       no       4         2      2     1     1       2         4  19  19  20
48      GP   M   15       U     GT3       T     4     2   teacher     other        home   mother           1          2         0        no    yes  yes         no     yes    yes       no       no       4         3      3     2     2       5         2  15  15  14
49      GP   F   15       U     GT3       T     4     4  services   teacher       other   father           1          2         1       yes    yes   no        yes      no    yes      yes       no       4         4      4     1     1       3         2   7   7   7
50      GP   F   16       U     LE3       T     2     2  services  services      course   mother           3          2         0        no    yes  yes         no     yes    yes      yes       no       4         3      3     2     3       4         2  12  13  13
51      GP   F   15       U     LE3       T     4     2    health     other       other   mother           1          2         0        no    yes  yes         no     yes    yes      yes       no       4         3      3     1     1       5         2  11  13  13
52      GP   M   15       U     LE3       A     4     2    health    health       other   father           2          1         1        no     no   no         no     yes    yes       no       no       5         5      5     3     4       5         6  11  11  10
53      GP   F   15       U     GT3       T     4     4  services  services      course   mother           1          1         0       yes    yes  yes         no     yes    yes      yes       no       3         3      4     2     3       5         0   8  10  11
54      GP   F   15       U     LE3       A     3     3     other     other       other   mother           1          1         0        no     no  yes         no     yes    yes      yes       no       5         3      4     4     4       1         6  10  13  13
55      GP   F   16       U     GT3       A     2     1     other     other       other   mother           1          2         0        no     no  yes        yes     yes    yes      yes      yes       5         3      4     1     1       2         8   8   9  10
56      GP   F   15       U     GT3       A     4     3  services  services  reputation   mother           1          2         0        no    yes  yes        yes     yes    yes      yes       no       4         3      2     1     1       1         0  14  15  15
57      GP   M   15       U     GT3       T     4     4   teacher    health  reputation   mother           1          2         0        no    yes   no        yes     yes    yes       no       no       3         2      2     1     1       5         4  14  15  15
58      GP   M   15       U     LE3       T     1     2     other   at_home        home   father           1          2         0       yes    yes   no        yes     yes    yes      yes       no       4         3      2     1     1       5         2   9  10   9
59      GP   F   16       U     GT3       T     4     2  services     other      course   mother           1          2         0        no    yes   no         no     yes    yes      yes       no       4         2      3     1     1       5         2  15  16  16
60      GP   F   16       R     GT3       T     4     4    health   teacher       other   mother           1          2         0        no    yes   no        yes     yes    yes       no       no       2         4      4     2     3       4         6  10  11  11
61      GP   F   16       U     GT3       T     1     1  services  services      course   father           4          1         0       yes    yes   no        yes      no    yes      yes      yes       5         5      5     5     5       5         6  10   8  11
62      GP   F   16       U     LE3       T     1     2     other  services  reputation   father           1          2         0       yes     no   no        yes     yes    yes      yes       no       4         4      3     1     1       1         4   8  10   9
63      GP   F   16       U     GT3       T     4     3   teacher    health        home   mother           1          3         0       yes    yes  yes        yes     yes    yes      yes       no       3         4      4     2     4       4         2  10   9   9
64      GP   F   15       U     LE3       T     4     3  services  services  reputation   father           1          2         0       yes     no   no        yes     yes    yes      yes      yes       4         4      4     2     4       2         0  10  10  10
65      GP   F   16       U     LE3       T     4     3   teacher  services      course   mother           3          2         0        no    yes   no        yes     yes    yes      yes       no       5         4      3     1     2       1         2  16  15  15
66      GP   M   15       U     GT3       A     4     4     other  services  reputation   mother           1          4         0        no    yes   no        yes      no    yes      yes      yes       1         3      3     5     5       3         4  13  13  12
67      GP   F   16       U     GT3       T     3     1  services     other      course   mother           1          4         0       yes    yes  yes         no     yes    yes      yes       no       4         3      3     1     2       5         4   7   7   6
68      GP   F   15       R     LE3       T     2     2    health  services  reputation   mother           2          2         0       yes    yes  yes         no     yes    yes      yes       no       4         1      3     1     3       4         2   8   9   8
69      GP   F   15       R     LE3       T     3     1     other     other  reputation   father           2          4         0        no    yes   no         no      no    yes      yes       no       4         4      2     2     3       3        12  16  16  16
70      GP   M   16       U     GT3       T     3     1     other     other  reputation   father           2          4         0        no    yes  yes         no     yes    yes      yes       no       4         3      2     1     1       5         0  13  15  15
71      GP   M   15       U     GT3       T     4     2     other     other      course   mother           1          4         0        no     no   no         no     yes    yes      yes       no       3         3      3     1     1       3         0  10  10  10
72      GP   F   15       R     GT3       T     1     1     other     other  reputation   mother           1          2         2       yes    yes   no         no      no    yes      yes      yes       3         3      4     2     4       5         2   8   6   5
73      GP   M   16       U     GT3       T     3     1     other     other  reputation   mother           1          1         0        no     no   no        yes     yes    yes       no       no       5         3      2     2     2       5         2  12  12  14
74      GP   F   16       U     GT3       T     3     3     other  services        home   mother           1          2         0       yes    yes  yes        yes     yes    yes      yes       no       4         3      3     2     4       5        54  11  12  11

Reading Json data in Pandas

In [60]:
import pandas as pd

df = pd.read_json('data.json')

print(df.to_string())

                  student Bio student Academics student Academics1
first name                  A               NaN                NaN
last name                   B               NaN                NaN
DOB                                         NaN                NaN
address     {'city': 'Hubli'}               NaN                NaN
grade1                    NaN                A+                NaN
grade2                    NaN                A+                NaN
grade3                    NaN                A+                NaN
grade4                    NaN               NaN                 A+
grade5                    NaN               NaN                 A+
grade6                    NaN               NaN                 A+

In [62]:
import pandas as pd

data = {
    "Duration":{
        "0":60,
        "1":60,
        "2":60,
        "3":45,
        "4":45,
        "5":60
        },
    "Pulse":{
        "0":110,
        "1":117,
        "2":103,
        "3":109,
        "4":117,
        "5":102
        },
    "Maxpulse":{
        "0":130,
        "1":145,
        "2":135,
        "3":175,
        "4":148,
        "5":127
        },
    "Calories":{
        "0":409,
        "1":479,
        "2":340,
        "3":282,
        "4":406,
        "5":300
        }
}

df = pd.DataFrame(data)

print(df)

   Duration  Pulse  Maxpulse  Calories
0        60    110       130       409
1        60    117       145       479
2        60    103       135       340
3        45    109       175       282
4        45    117       148       406
5        60    102       127       300

In [1]:
import pandas as pd

df = pd.read_csv('student_data.csv')

print(df.head(10))

  school sex  age address famsize Pstatus  Medu  Fedu      Mjob      Fjob  \
0     GP   F   18       U     GT3       A     4     4   at_home   teacher
1     GP   F   17       U     GT3       T     1     1   at_home     other
2     GP   F   15       U     LE3       T     1     1   at_home     other
3     GP   F   15       U     GT3       T     4     2    health  services
4     GP   F   16       U     GT3       T     3     3     other     other
5     GP   M   16       U     LE3       T     4     3  services     other
6     GP   M   16       U     LE3       T     2     2     other     other
7     GP   F   17       U     GT3       A     4     4     other   teacher
8     GP   M   15       U     LE3       A     3     2  services     other
9     GP   M   15       U     GT3       T     3     4     other     other

   ... famrel freetime  goout  Dalc  Walc health absences  G1  G2  G3
0  ...      4        3      4     1     1      3        6   5   6   6
1  ...      5        3      3     1     1      3        4   5   5   6
2  ...      4        3      2     2     3      3       10   7   8  10
3  ...      3        2      2     1     1      5        2  15  14  15
4  ...      4        3      2     1     2      5        4   6  10  10
5  ...      5        4      2     1     2      5       10  15  15  15
6  ...      4        4      4     1     1      3        0  12  12  11
7  ...      4        1      4     1     1      1        6   6   5   6
8  ...      4        2      2     1     1      1        0  16  18  19
9  ...      5        5      1     1     1      5        0  14  15  15

[10 rows x 33 columns]

In [2]:
print(df.head())

  school sex  age address famsize Pstatus  Medu  Fedu     Mjob      Fjob  ...  \
0     GP   F   18       U     GT3       A     4     4  at_home   teacher  ...
1     GP   F   17       U     GT3       T     1     1  at_home     other  ...
2     GP   F   15       U     LE3       T     1     1  at_home     other  ...
3     GP   F   15       U     GT3       T     4     2   health  services  ...
4     GP   F   16       U     GT3       T     3     3    other     other  ...

  famrel freetime  goout  Dalc  Walc health absences  G1  G2  G3
0      4        3      4     1     1      3        6   5   6   6
1      5        3      3     1     1      3        4   5   5   6
2      4        3      2     2     3      3       10   7   8  10
3      3        2      2     1     1      5        2  15  14  15
4      4        3      2     1     2      5        4   6  10  10

[5 rows x 33 columns]

In [3]:
print(df.tail(10))

    school sex  age address famsize Pstatus  Medu  Fedu      Mjob      Fjob  \
385     MS   F   18       R     GT3       T     2     2   at_home     other
386     MS   F   18       R     GT3       T     4     4   teacher   at_home
387     MS   F   19       R     GT3       T     2     3  services     other
388     MS   F   18       U     LE3       T     3     1   teacher  services
389     MS   F   18       U     GT3       T     1     1     other     other
390     MS   M   20       U     LE3       A     2     2  services  services
391     MS   M   17       U     LE3       T     3     1  services  services
392     MS   M   21       R     GT3       T     1     1     other     other
393     MS   M   18       R     LE3       T     3     2  services     other
394     MS   M   19       U     LE3       T     1     1     other   at_home

     ... famrel freetime  goout  Dalc  Walc health absences  G1  G2  G3
385  ...      5        3      3     1     3      4        2  10   9  10
386  ...      4        4      3     2     2      5        7   6   5   6
387  ...      5        4      2     1     2      5        0   7   5   0
388  ...      4        3      4     1     1      1        0   7   9   8
389  ...      1        1      1     1     1      5        0   6   5   0
390  ...      5        5      4     4     5      4       11   9   9   9
391  ...      2        4      5     3     4      2        3  14  16  16
392  ...      5        5      3     3     3      3        3  10   8   7
393  ...      4        4      1     3     4      5        0  11  12  10
394  ...      3        2      3     3     3      5        5   8   9   9

[10 rows x 33 columns]

In [4]:
print(df.tail())

    school sex  age address famsize Pstatus  Medu  Fedu      Mjob      Fjob  \
390     MS   M   20       U     LE3       A     2     2  services  services
391     MS   M   17       U     LE3       T     3     1  services  services
392     MS   M   21       R     GT3       T     1     1     other     other
393     MS   M   18       R     LE3       T     3     2  services     other
394     MS   M   19       U     LE3       T     1     1     other   at_home

     ... famrel freetime  goout  Dalc  Walc health absences  G1  G2  G3
390  ...      5        5      4     4     5      4       11   9   9   9
391  ...      2        4      5     3     4      2        3  14  16  16
392  ...      5        5      3     3     3      3        3  10   8   7
393  ...      4        4      1     3     4      5        0  11  12  10
394  ...      3        2      3     3     3      5        5   8   9   9

[5 rows x 33 columns]